# Generated by Django 2.1.5 on 2019-01-13 08:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Home name')),
                ('full_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Full name')),
                ('dog_sex', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Dog sex')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('pedigree', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Pedigree')),
                ('picture', models.ImageField(upload_to='media/__image_upload/dog/picture')),
                ('our_dog', models.BooleanField(blank=True, default=True, verbose_name='Our dog')),
            ],
            options={
                'verbose_name': 'Dog',
            },
        ),
    ]
