# Generated by Django 2.1.5 on 2019-01-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_showresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='show_results', to='dog.Dog', verbose_name='Dog')),
            ],
            options={
                'verbose_name': 'Show result',
            },
        ),
        migrations.DeleteModel(
            name='ShowResults',
        ),
    ]
