# Generated by Django 2.1.5 on 2019-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_showresult_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='showresult',
            name='show_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Show id'),
        ),
        migrations.AddField(
            model_name='showresult',
            name='show_judge',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Show judge'),
        ),
        migrations.AddField(
            model_name='showresult',
            name='show_locale',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Show locale'),
        ),
        migrations.AddField(
            model_name='showresult',
            name='show_result',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Show result'),
        ),
        migrations.AlterField(
            model_name='showresult',
            name='show_date',
            field=models.DateField(blank=True, null=True, verbose_name='Show date'),
        ),
    ]
