# Generated by Django 2.1.5 on 2019-01-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dog', '0007_auto_20190115_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('dog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dog.Dog')),
            ],
            options={
                'verbose_name': 'Boy',
            },
            bases=('dog.dog',),
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('dog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dog.Dog')),
            ],
            options={
                'verbose_name': 'Girl',
            },
            bases=('dog.dog',),
        ),
        migrations.AddField(
            model_name='dog',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_dog.dog_set+', to='contenttypes.ContentType'),
        ),
    ]
