# Generated by Django 2.1.5 on 2019-01-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0010_auto_20190115_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Name')),
                ('p_sex', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='P sex')),
                ('Status', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Status')),
                ('dad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dog.Boy', verbose_name='Dad')),
                ('mom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dog.Girl', verbose_name='Mom')),
            ],
            options={
                'verbose_name': 'Puppy',
            },
        ),
    ]
