# Generated by Django 2.1.5 on 2019-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0011_puppy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='Status',
            field=models.CharField(blank=True, choices=[('Avalable', 'Avalable'), ('Girl', 'Girl')], default='', max_length=8, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='p_sex',
            field=models.CharField(blank=True, choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default='', max_length=4, null=True, verbose_name='P sex'),
        ),
    ]
