# Generated by Django 2.1.5 on 2019-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0012_auto_20190115_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='Status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Girl', 'Girl')], default='', max_length=9, null=True, verbose_name='Status'),
        ),
    ]
