# Generated by Django 2.1.5 on 2019-01-15 13:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('dog', '0018_auto_20190115_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuppieParents',
            new_name='PuppieParent',
        ),
        migrations.AlterModelOptions(
            name='puppieparent',
            options={'verbose_name': 'Puppie parent'},
        ),
    ]
