# Generated by Django 2.1.5 on 2019-01-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0019_auto_20190115_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='group',
        ),
        migrations.AddField(
            model_name='puppy',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dog.PuppieParent', verbose_name='Parents'),
        ),
    ]
