# Generated by Django 2.1.5 on 2019-01-15 13:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0020_auto_20190115_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title')),
                ('home_text', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Home text')),
            ],
            options={
                'verbose_name': 'Content',
            },
        ),
    ]
