# Generated by Django 2.1.5 on 2019-01-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0021_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Breed description',
            },
        ),
    ]
