# Generated by Django 2.1.5 on 2019-01-15 13:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0022_breeddescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Date created')),
                ('news_text', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='News text')),
            ],
            options={
                'verbose_name': 'News',
            },
        ),
        migrations.AddField(
            model_name='breeddescription',
            name='br_descript',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Br descript'),
        ),
    ]
