# Generated by Django 2.1.5 on 2019-01-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0023_auto_20190115_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'New'},
        ),
    ]
