# Generated by Django 2.1.5 on 2019-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0025_photogallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='gellery',
            field=models.ImageField(blank=True, null=True, upload_to='media/__image_upload/dog/galleryfoto'),
        ),
    ]
