# Generated by Django 2.1.5 on 2019-01-15 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0027_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Name')),
                ('mail', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mail')),
                ('text', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Contact form',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Link',
            },
        ),
        migrations.CreateModel(
            name='MyBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_text', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Html text')),
            ],
            options={
                'verbose_name': 'My banner',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='e_mail',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='E mail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='kennel',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Kennel'),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner1',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Owner1'),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Owner2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='skype',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Skype'),
        ),
    ]
