# Generated by Django 2.1.5 on 2019-01-15 14:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0029_auto_20190115_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='banner',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Banner'),
        ),
    ]
