# Generated by Django 2.1.5 on 2019-01-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0030_auto_20190115_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='skype',
        ),
    ]
