# Generated by Django 2.1.5 on 2019-01-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0031_remove_contact_skype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
