# Generated by Django 2.1.5 on 2019-01-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0033_auto_20190125_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybanner',
            name='html_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Html text'),
        ),
    ]
