# Generated by Django 2.1.5 on 2019-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0034_auto_20190125_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybanner',
            name='html_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Html text'),
        ),
    ]
