# Generated by Django 2.1.5 on 2019-01-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0036_auto_20190126_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='banner',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Banner'),
        ),
    ]
