# Generated by Django 2.1.5 on 2019-01-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0037_auto_20190126_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='picture',
            new_name='foto',
        ),
    ]
