# Generated by Django 2.1.5 on 2019-01-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0038_auto_20190126_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/dog/picture'),
        ),
        migrations.AlterField(
            model_name='dogpicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/dog/dogfoto'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='gellery',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/dog/galleryfoto'),
        ),
        migrations.AlterField(
            model_name='puppypicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/dog/puppiesfoto'),
        ),
    ]
