# Generated by Django 2.1.5 on 2019-01-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0039_auto_20190127_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/dog_foto'),
        ),
        migrations.AlterField(
            model_name='dogpicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/dog_picture'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='gellery',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/gallery_foto'),
        ),
        migrations.AlterField(
            model_name='puppypicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dog/media/__image_upload/puppies_foto'),
        ),
    ]
