# Generated by Django 2.1.5 on 2019-01-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0040_auto_20190127_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='pedigree',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Pedigree'),
        ),
    ]
