# Generated by Django 2.1.5 on 2019-01-27 20:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0041_auto_20190127_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='pedigree',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Pedigree'),
        ),
    ]
