# Generated by Django 2.1.5 on 2019-02-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0043_auto_20190128_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photogallery',
            old_name='gellery',
            new_name='gallery',
        ),
    ]
