# Generated by Django 2.1.5 on 2019-02-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0044_auto_20190205_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puppies', to='dog.PuppieParent', verbose_name='Parents'),
        ),
        migrations.AlterField(
            model_name='puppypicture',
            name='puppy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puppy_pictures', to='dog.Puppy', verbose_name='Puppy'),
        ),
    ]
