# Generated by Django 2.1.5 on 2019-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0045_auto_20190206_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='Status',
        ),
        migrations.AddField(
            model_name='puppy',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold')], default='', max_length=9, null=True, verbose_name='Status'),
        ),
    ]
