# Generated by Django 2.1.5 on 2019-08-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0048_auto_20190330_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='zvonok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zvonok'),
        ),
    ]
