# Generated by Django 2.1.5 on 2019-08-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0051_contact_zvonok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='zvonok',
        ),
    ]
